# базовый образ для фронтенда
FROM node:18-alpine

# копирование и установка зависимостей
WORKDIR /var/www/frontend

COPY frontend/package.json .

RUN yarn install

# сборка фронтенда
COPY frontend .
RUN yarn build

# запуск веб-сервера
CMD yarn dev --host