version: '3'
services:
  # PHP Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    tty: true
    working_dir: /var/www/backend
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
    volumes:
      - ./backend:/var/www/backend
      - ./conf/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
      - redis
    networks:
      - app

  # Nginx Service
  nginx:
    image: nginx:alpine
    tty: true
    ports:
      - "8000:8000"
      - "443:443"
    volumes:
      - ./backend:/var/www/backend
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - mysql
      - redis
    networks:
      - app

  # Node Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/var/www/frontend
      - /var/www/frontend/node_modules
    depends_on:
      - nginx
    networks:
      - app

  # MySQL Service
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: chagle
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - app

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
    networks:
      - app

  # Redis Service
  redis:
    image: redis:6.2
    ports:
      - '6379:6379'
    networks:
      - app

  # Mailhog Service
  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - app

networks:
  app:
    driver: bridge